// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClPICp3Jahk_DaZNhVE00sATFHYXkBKhE',
    appId: '1:331182416136:web:adfa776ec69e5162d68cbd',
    messagingSenderId: '331182416136',
    projectId: 'flutterproject-2c7a7',
    authDomain: 'flutterproject-2c7a7.firebaseapp.com',
    storageBucket: 'flutterproject-2c7a7.appspot.com',
    measurementId: 'G-Y9X393L1J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp4FG1p1e6xIw1iqzNM7hx_Dduj5CKNvg',
    appId: '1:331182416136:android:e655ee76fa4d45c2d68cbd',
    messagingSenderId: '331182416136',
    projectId: 'flutterproject-2c7a7',
    storageBucket: 'flutterproject-2c7a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK96iAhjIInAweYC_5ivtxuar_3LzVB5w',
    appId: '1:331182416136:ios:8f8bc0644ebf2513d68cbd',
    messagingSenderId: '331182416136',
    projectId: 'flutterproject-2c7a7',
    storageBucket: 'flutterproject-2c7a7.appspot.com',
    iosClientId: '331182416136-fk0pqang4qqb1ucfpra5auion8alu1go.apps.googleusercontent.com',
    iosBundleId: 'com.example.practicaFlutter',
  );
}
